apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: summit-db-logical-replica-backup
  namespace: summit-db-logical-replica
spec:
  immediate: true
  schedule: "0 0 4 * * *"
  backupOwnerReference: self
  cluster:
    name: summit-db-logical-replica