apiVersion: v1
kind: Service
metadata:
  name: summit-logical-replica-db-svc
  namespace: summit-db-logical-replica
  annotations: 
    metallb.io/address-pool: sdf-rubin-ingest
    metallb.io/ip-allocated-from-pool: sdf-rubin-ingest
    metallb.io/loadBalancerIPs: 172.24.10.11
spec:
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: pgbouncer
    port: 5432
  selector:
    cnpg.io/cluster: summit-logical-replica
    cnpg.io/instanceRole: primary
