apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: sdf-services
  labels:
    cnpg.io/cluster: summit-db-logical-replica
  name: summit-db-logical-replica-svc
  namespace: summit-db-logical-replica
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 172.24.5.86
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgresql: summit-db-logical-replica
    role: primary
  type: LoadBalancer
