apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: summit-db-replica
  namespace: summit-db-replica
spec:
  affinity:
    podAntiAffinityType: preferred
    topologyKey: ""
  bootstrap:
    pg_basebackup:
      database: ""
      owner: ""
      source: cnpg-cluster
  enableSuperuserAccess: true
  externalClusters:
  - connectionParameters:
      host: db-lhn.cp.lsst.org
      user: replicauser
    name: cnpg-cluster
    password:
      key: password
      name: source-db-replicauser
  failoverDelay: 0
  imageName: docker.io/cbarria/cnpgsphere:14.5
  imagePullPolicy: Always
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true'
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: always
      archive_timeout: 5min
      dynamic_shared_memory_type: posix
      idle_session_timeout: 4h
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_connections: "500"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_buffers: 256MB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      wal_keep_size: 512MB
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    pg_hba:
    - host all all 139.229.134.0/23 md5
    - host all all 139.229.136.0/21 md5
    - host all all 139.229.144.0/20 md5
    - host all all 139.229.160.0/19 md5
    - host all all 139.229.192.0/18 md5
    - host all all 140.252.146.0/23 md5
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  replica:
    enabled: true
    source: cnpg-cluster
  resources: {}
  startDelay: 30
  stopDelay: 30
  storage:
    resizeInUseVolumes: true
    size: 5Gi
  switchoverDelay: 40000000