apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2025-06-03T15:09:37-05:00"
  name: summit-db-logical-replica
  namespace: summit-db-logical-replica
spec:
  affinity:
    podAntiAffinityType: preferred
    topologyKey: ""
  backup:
    barmanObjectStore:
      destinationPath: s3://rubin-summit-db-logical-replica
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: s3-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: s3-creds
    retentionPolicy: 15d
    target: prefer-standby
  bootstrap:
    initdb:
      database: exposurelog
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: rubin
      secret:
        name: usdf-summitdb-logical-replication-creds
  enablePDB: true
  enableSuperuserAccess: true
  failoverDelay: 0
  imageName: ghcr.io/lsst-sqre/cnpg-postgres-images:16.3
  imagePullPolicy: Always
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: "true"
  instances: 2
  logLevel: info
  maxSyncReplicas: 0
  minSyncReplicas: 0
  monitoring:
    customQueriesConfigMap:
    - key: queries
      name: cnpg-default-monitoring
    disableDefaultQueries: false
    enablePodMonitor: false
  postgresGID: 26
  postgresUID: 26
  postgresql:
    parameters:
      archive_mode: "on"
      archive_timeout: 5min
      checkpoint_timeout: "3600"
      dynamic_shared_memory_type: posix
      full_page_writes: "on"
      idle_session_timeout: 4h
      log_destination: csvlog
      log_directory: /controller/log
      log_filename: postgres
      log_rotation_age: "0"
      log_rotation_size: "0"
      log_truncate_on_rotation: "false"
      logging_collector: "on"
      max_connections: "500"
      max_logical_replication_workers: "10"
      max_parallel_workers: "32"
      max_replication_slots: "32"
      max_worker_processes: "32"
      shared_buffers: 256MB
      shared_memory_type: mmap
      shared_preload_libraries: ""
      ssl_max_protocol_version: TLSv1.3
      ssl_min_protocol_version: TLSv1.3
      wal_keep_size: 512MB
      wal_level: logical
      wal_log_hints: "on"
      wal_receiver_timeout: 5s
      wal_sender_timeout: 5s
    pg_hba:
    - host all all 139.229.134.0/23 md5
    - host all all 139.229.136.0/21 md5
    - host all all 139.229.144.0/20 md5
    - host all all 139.229.160.0/19 md5
    - host all all 139.229.192.0/18 md5
    - host all all 140.252.146.0/23 md5
    syncReplicaElectionConstraint:
      enabled: false
  primaryUpdateMethod: restart
  primaryUpdateStrategy: unsupervised
  replicationSlots:
    highAvailability:
      enabled: true
      slotPrefix: _cnpg_
    synchronizeReplicas:
      enabled: true
    updateInterval: 30
  smartShutdownTimeout: 180
  startDelay: 30
  stopDelay: 30
  storage:
    resizeInUseVolumes: true
    size: 200Gi
  switchoverDelay: 40000000
