
apiVersion: v1
kind: Service
metadata:
  labels:
    cnpg.io/cluster: summit-db-replica
  name: cnpg-loadbalancer
  namespace: summit-db-replica
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    postgresql: summit-db-replica
    role: primary
  sessionAffinity: None
  type: LoadBalancer
